apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3001
        env:
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: spotify-creds
              key: SPOTIFY_CLIENT_ID
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: spotify-creds
              key: SPOTIFY_CLIENT_SECRET
        - name: SPOTIFY_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: spotify-creds
              key: SPOTIFY_REDIRECT_URI
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_DB
          value: "rekordbox"
        - name: POSTGRES_USER
          value: "rekordboxuser"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.db.password }}"

