apiVersion: v1
kind: Secret
metadata:
  name: spotify-creds
type: Opaque
data:
  SPOTIFY_CLIENT_ID: {{ .Values.spotify.clientId | b64enc }}
  SPOTIFY_CLIENT_SECRET: {{ .Values.spotify.clientSecret | b64enc }}
  SPOTIFY_REDIRECT_URI: {{ .Values.spotify.redirectUri | b64enc }}
